### ISSUE TITLE
Health Pack Benefit Reported Glitch

### ISSUE THREAD

**Issue by fearts** [War3Evo/TF2-Super-Smash-Bros#5]
Had one of my admins send me this:

12:21 AM - Chikiro: hey fire, playing on the beta smash server, i noticed that one of the healthpack "benefits" isnt working properly.  When you get the "slowed" one, it doesnt actually slow you until you change weapons.  Then, if you do get slowed, you dont go back to the normal speed until after changing weps again.

**Comment by War3Evo** [comment]
Built a new speed engine in the sb_item_spawner.sp file.  This should solve any speed related issues and add more flexibility to create new speed power up items.  I will be testing this today.
